name: Integration test

on:
  push:
    branches:
      - main

jobs:
  run_integration_tests:
    runs-on: ubuntu-18-04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm install
    - name: run integration tests
      run: npm run test